loginapp/urls.py
from django.urls import path

from . import views


app_name = 'loginapp'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('signup', views.signup, name='signup'),
    path('password_reset', views.password_reset, name='password_reset'),
]

twitterapp/urls.py
from django.urls import path

from . import views


app_name = 'twitterapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('details/<int:pk>', views.details, name='details'),
    path('profile', views.profile, name='profile'),
]

twitterproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('loginapp.urls', namespace='loginapp')),
    path('twitter/', include('twitterapp.urls', namespace='twitterapp')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

loginapp/models.py
from django.db import models

# Create your models here.

twitterapp/models.py
from django.db import models
from django.contrib.auth.models import User


class TweetItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    status = models.BooleanField()
    description = models.TextField(blank=True)

    def __str__(self):
        return f"{self.pk}:{self.title}, by {self.user}"

loginapp/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout

from .utils import random_string


def login(request):
    context = {}
    if request.method == 'POST':
        user = authenticate(request, 
            username=request.POST['user'], 
            password=request.POST['password'])
        if user:
            dj_login(request, user)
            # is this just stupid? context = {'user':request.POST['user']}
            return HttpResponseRedirect(reverse('twitterapp:index'))
        else:
            #context = {'error':'Username or password is wrong.'}
            context['error'] = 'Username or password is wrong.'

    return render(request, 'loginapp/login.html', context)

def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('loginapp:login'))


def signup(request):
    if User.is_authenticated:
        dj_logout(request)
    context = {}
    if request.method == 'POST':
        if not request.POST['password'] == request.POST['repeatpassword']:
            context['error'] = 'Passwords do not match.'
            return render(request, 'loginapp/signup.html', context)
        if len(User.objects.filter(username=request.POST['user'])) > 0:
            context['error'] = 'Username already exists.'
            return render(request, 'loginapp/signup.html', context)
        if len(User.objects.filter(email=request.POST['email'])) > 0:
            context['error'] = 'Email already exists.'
            return render(request, 'loginapp/signup.html', context)
        user = User.objects.create_user(request.POST['user'],password=request.POST['password'], email=request.POST['email'])
        user.save()
        dj_login(request, user)
        return HttpResponseRedirect(reverse('twitterapp:index'))

    return render(request, 'loginapp/signup.html')



def password_reset(request):
    context = {}
    if request.method == 'POST':
        users = User.objects.filter(username=request.POST['user'])
        if users:
            user = users[0]
            new_password = random_string()
            user.set_password(new_password)
            user.save()
            print(f'**** User {user} change password to {new_password}')
            return HttpResponseRedirect(reverse('loginapp:login'))
        else:
            context['error'] = 'No such username.'
        
    return render(request, 'loginapp/password_reset.html', context)

twitterapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.urls import reverse

from .models import *


@login_required
def index(request):
    if request.method == 'GET':
        tweet_items = TweetItem.objects.all()
        context = {
            'tweets': tweet_items
        }
        return render(request, 'twitterapp/index.html', context)

    if request.method == 'POST':
        tweet_item = TweetItem()
        tweet_item.title = request.POST['title']
        tweet_item.description = request.POST['description']
        tweet_item.status = False
        tweet_item.user = request.user
        tweet_item.save()
        return HttpResponseRedirect(reverse('twitterapp:index'))

    return HttpResponseBadRequest()


@login_required
def profile(request):
    if request.method == 'GET':
        tweet_items = TweetItem.objects.filter(user=request.user)
        context = {
            'tweets': tweet_items
        }
        return render(request, 'twitterapp/profile.html', context)

    if request.method == 'POST':
        tweet_item = TweetItem()
        tweet_item.title = request.POST['title']
        tweet_item.description = request.POST['description']
        tweet_item.status = False
        tweet_item.user = request.user
        tweet_item.save()
        return HttpResponseRedirect(reverse('twitterapp:profile'))

    return HttpResponseBadRequest()

@login_required
def details(request, pk):
    tweet = get_object_or_404(TweetItem, pk=pk, user=request.user)

    if request.method == 'GET':
        context = {
            'tweet': tweet
        }
        return render(request, 'twitterapp/details.html', context)

    if request.method == 'POST':
        tweet.title = request.POST['title']
        tweet.description = request.POST['description']
        status = request.POST.getlist('status')
        if len(status) > 0:
            tweet.status = True
        else:
            tweet.status = False
        tweet.save()
        return HttpResponseRedirect(reverse('twitterapp:index'))

    return HttpResponseBadRequest()

loginapp/templates/loginapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="stylesheet" href="../../static/loginapp/style.css">
</head>
<body>
    <h1>Login</h1>
    {{user}}
    <form action="." method="POST">
        {% csrf_token %}
        <label for="user">Username</label>
        <br />
        <input type="text" id="user" name="user" placeholder="User Name">
        <br />
        <label for="password">Password</label>
        <br />
        <input type="password" id="password" name="password" placeholder="Password">
        <br />
        <input type="submit" value="Submit">
    </form>
    {% if error %}
        <p class="error">{{ error }}</p>
        <p><a href="{% url 'loginapp:password_reset' %}">Reset your password</a></p>
    {% endif  %}
    <hr>
    <a href="{% url 'loginapp:signup' %}">Sign up</a>
</body>
</html>

loginapp/templates/loginapp/password_reset.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Password Reset</title>
    <link rel="stylesheet" href="../../static/loginapp/style.css">
</head>
<body>
    <h1>Password Reset</h1>
    {{user}}
    <form action="{% url 'loginapp:password_reset'  %}" method="POST">
        {% csrf_token %}
        <label for="user">Username</label>
        <br />
        <input type="text" id="user" name="user" placeholder="User Name">
        <br />
        <input type="submit" value="Submit">
    </form>
    {% if error %}
        <p class="error">{{ error }}</p>
    {% endif  %}
    <hr>
</body>
</html>

loginapp/templates/loginapp/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign-up</title>
    <link rel="stylesheet" href="../../static/loginapp/style.css">
</head>
<body>
    <h1>Sign-up</h1>
    <hr>
    <form action="{% url 'loginapp:signup' %}" method="POST">
            {% csrf_token %}
            <label for="user">Username</label>
            <br />
            <input type="text" id="user" name="user" placeholder="User Name">
            <br />
            <label for="email">Email</label>
            <br />
            <input type="email" id="email" name="email" placeholder="E-mail">
            <br />
            <label for="password">Password</label>
            <br />
            <input type="password" id="password" name="password" placeholder="Password">
            <br />
            <label for="repeatpassword">Repeat Password</label>
            <br />
            <input type="password" id="repeatpassword" name="repeatpassword" placeholder="Repeat Password">
            <br />
            <input type="submit" value="Submit">
        </form>
    </body>
</html>

twitterapp/templates/twitterapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Twitter</title>
    <link rel="stylesheet" href="../../static/twitterapp/style.css">
</head>
<body>
    <nav>
        <!-- <div>Logo</div> -->
        <img src="{% static 'twitterapp/logo.png' %}" alt="">
        <a href="{% url 'twitterapp:profile' %}">My profile</a>
        <a href="{% url 'loginapp:logout' %}">Log out</a>
    </nav>
    <div class="wrapper">
    <h1>Tweet feed</h1>
    <br>
    <form action="." method="post" id="tweetForm">
            {% csrf_token  %}
            <textarea name="description" placeholder="What's up {{tweet.user }}?" id="description">{{ tweet.description }}</textarea>
            <br />
            <button>Tweet</button>
    </form>
    <ul>
        {% for tweet in tweets  %}
            <h2>{{ tweet.user }} <i>tweets:</i></h2>
            <div class="tweetBox">
                <div class="arrow"></div>
                <div class="tweet">
                    <p>{{ tweet.description }}</p>
                </div>
            </div>
        {% endfor  %}
    </ul>
    </div>
</body>
</html>

twitterapp/templates/twitterapp/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Twitter</title>
    <link rel="stylesheet" href="../../static/twitterapp/style.css">
</head>
<body>
    <nav>
        <img src="{% static 'twitterapp/logo.png' %}" alt="">
        <a href="{% url 'twitterapp:index' %}">Tweet feed</a>
        <a href="{% url 'loginapp:logout' %}">Log out</a>
    </nav>
    <div class="wrapper">
    <h1>Profile of {{ user }}</h1>
    <br>
    <ul>
        {% for tweet in tweets  %}
        <h2>{{ tweet.user }} <i>tweets:</i></h2>
        <div class="tweetBox">
            <div class="arrow"></div>
                <div class="tweet">
                <p>{{ tweet.description }}</p>
            </div>
        </div>
        {% endfor  %}
    </ul>
    <div id="account">
        <h2>Account info:</h2>
        <p>User name: {{ user }}</p>
        <p>Email: {{ user.email }}</p>
    </div>
</div>
</body>
</html>